version: '3'
services:
    steerdmetastore:
      image: steerd-postgresql:${GATEWAY_VERSION}
      container_name: steerdmetastore
      environment:
        - POSTGRES_DB=prestogateway
        - POSTGRES_USER=prestogateway
        - POSTGRES_PASSWORD=$PGPASSWORD
      ports:
        - "5432:5432"
      volumes:
        - /var/folders/qv/z_hlhdmj01jf4l_8jd4dvht40000gn/T/tmp.WACqJGRJ:/var/lib/postgresql/data
      networks:
        - default
    postgres2:
      image: steerd-postgresql:${GATEWAY_VERSION}
      container_name: postgres2
      environment:
        - POSTGRES_DB=prestogateway
        - POSTGRES_USER=prestogateway
        - POSTGRES_PASSWORD=$PGPASSWORD
      ports:
        - "5433:5432"
      volumes:
        - steerd-postgresql-vol1:/var/lib/postgresql/data
      networks:
        - default
      depends_on:
        - steerdmetastore
    hivemetastore:
      container_name: hivemetastore
      image: hivemetastore:${GATEWAY_VERSION}
      env_file:
        - ${HADOOP_HIVE_ENV_FILE}
      environment:
        - SERVICE_PRECONDITION=steerdmetastore:5432
      volumes:
        - /var/folders/qv/z_hlhdmj01jf4l_8jd4dvht40000gn/T/tmp.aFhIB7qR:/tmp
      ports:
        - "9083:9083"
      networks:
        - default
      depends_on:
        - steerdmetastore
    prestoserver:
      container_name: prestoserver
      image: prestosql/presto:334
      volumes:
        - ${PRESTO_CONFIG_DIR}:/etc/presto
        - /tmp/filedata:/tmp/filedata
      ports:
        - "8081:8080"
      networks:
        - default
      depends_on:
        - steerdmetastore
        - hivemetastore
    prestoserver2:
      container_name: prestoserver2
      image: prestosql/presto:334
      volumes:
        - ${PRESTO_CONFIG_DIR2}:/etc/presto
        - /tmp/filedata2:/tmp/filedata2
      ports:
        - "8082:8080"
      networks:
        - default
      depends_on:
        - steerdmetastore
        - hivemetastore
        - postgres2
        - prestoserver
    gateway:
      container_name: gateway
      image: gateway:${GATEWAY_VERSION}
      volumes:
        - ${GATEWAY_CONFIG_DIR}:/etc/presto-gateway:ro
        - /var/folders/qv/z_hlhdmj01jf4l_8jd4dvht40000gn/T/tmp.wOYN5xxd:/tmp
        - /var/folders/qv/z_hlhdmj01jf4l_8jd4dvht40000gn/T/tmp.2EQ0t5ek:/data
      environment:
        - SERVICE_PRECONDITION=steerdmetastore:5432 hivemetastore:9083
      ports:
        - "8080:8080"
      networks:
        - default
      depends_on:
        - steerdmetastore
        - hivemetastore
volumes:
  steerd-postgresql-vol:
  steerd-postgresql-vol1:
